### ISSUE TITLE
Tested on windows

### ISSUE THREAD

**Issue by VirtualSatai** [selbyk/pagesim#2]
I tested on windows under cygwin and GCC 4.9.2: make && ./pagesim.exe all 10
Apears to work fine, output was:
[...]
RANDOM Algorithm
Frames in Mem: 10, Hits: 831, Misses: 169, Hit Ratio: 0.831000
FIFO Algorithm
Frames in Mem: 10, Hits: 818, Misses: 182, Hit Ratio: 0.818000
LRU Algorithm
Frames in Mem: 10, Hits: 811, Misses: 189, Hit Ratio: 0.811000
CLOCK Algorithm
Frames in Mem: 10, Hits: 827, Misses: 173, Hit Ratio: 0.827000
NFU Algorithm
Frames in Mem: 10, Hits: 818, Misses: 182, Hit Ratio: 0.818000
AGING Algorithm
Frames in Mem: 10, Hits: 823, Misses: 177, Hit Ratio: 0.823000

**Comment by selbyk** [comment]
Cool, thanks!
